### ISSUE TITLE
Fibaro RGBW Controller not visible as light

### ISSUE THREAD

**Issue by kaugustyn** [alexander-vitishchenko/hc3-to-mqtt#13]
First of all - thanks for a great piece of integration, it was missed by many I suppose :)

I have issue with RGBW controller - it is somehow recognized, but only as power and energy source, an it should also be recognized as light/switch. Also  settings like color and brightness would be nice  :) 

I was trying to look at code and I think RGBW integration is on very early state, but my knowledge is very poor in this area to change anything here... 

Thanks

**Comment by alexander-vitishchenko** [comment]
Hi @kaugustyn

I've just released Fibaro RGBW device support - feel free to check it out and let me know if it works well for you!

**Comment by alexander-vitishchenko** [comment]
By the way - I've implemented passwordless mode to access Fibaro HC3. So you can remove these two redundant QA variables - "hc3Username" and "hc3Password"

Got inspired by another developer at Fibaro forum who apparently works on a similar integration

**Comment by alexander-vitishchenko** [comment]
+ I've additionally announced the QuickApp at Home Assistant forum (Third party integrations) - https://community.home-assistant.io/t/fibaro-home-center-3-hc3-integration/351615

**Comment by kaugustyn** [comment]
Hi 
I have done update but will test on morning. Also commented your post on HA forum, so hope it will help a little to promote your solution.

**Comment by alexander-vitishchenko** [comment]
Please let me know once you do the testing. It works for me, but your setup and use-cases could be different.

By the way - feel free to have a look at the alternative implementation mentioned at the thread https://forum.fibaro.com/topic/56231-fibaro-hc3-and-home-assistant-integration/. It would be great to see if it has any ideas or features that could be merged with the current implementation
