### ISSUE TITLE
Aeon Labs dimmable switches identified as regular on/off switches

### ISSUE THREAD

**Issue by tvamvaki** [alexander-vitishchenko/hc3-to-mqtt#14]
Excellent work and great app!

Work brilliantly with Fibaro branded devices however I have a few AEON Labs dimmiable switches which are being are only appearing as non-dimmable switches.

Manufacturer: AEON Labs
Type:com.fibaro.multilevelSwitch

**Comment by alexander-vitishchenko** [comment]
@tvamvaki let me try to add new device support

Can you please share device info from Swagger UI?

**Comment by tvamvaki** [comment]
{
  "id": 144,
  "name": "STUDY",
  "roomID": 220,
  "view": [
    {
      "assetsPath": "/dynamic-plugins/com.fibaro.multilevelSwitch/assets",
      "jsPath": "/dynamic-plugins/com.fibaro.multilevelSwitch",
      "name": "com.fibaro.multilevelSwitch",
      "translatesPath": "/dynamic-plugins/com.fibaro.multilevelSwitch/i18n",
      "type": "ts"
    },
    {
      "assetsPath": "/assets/icon",
      "jsPath": "/dynamic-plugins/level-change",
      "name": "level-change",
      "translatesPath": "/dynamic-plugins/level-change/i18n",
      "type": "ts"
    }
  ],
  "type": "com.fibaro.multilevelSwitch",
  "baseType": "com.fibaro.binarySwitch",
  "enabled": true,
  "visible": true,
  "isPlugin": false,
  "parentId": 143,
  "viewXml": false,
  "configXml": false,
  "interfaces": [
    "levelChange",
    "light",
    "zwave",
    "zwaveConfiguration",
    "zwaveMultiChannelAssociation",
    "zwaveSceneActivation",
    "zwaveSwitchAll"
  ],
  "properties": {
    "parameters": [
      {
        "id": 3,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      },
      {
        "id": 80,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      },
      {
        "id": 90,
        "lastReportedValue": 1,
        "lastSetValue": 1,
        "size": 1,
        "value": 1
      },
      {
        "id": 91,
        "lastReportedValue": 25,
        "lastSetValue": 25,
        "size": 2,
        "value": 25
      },
      {
        "id": 92,
        "lastReportedValue": 5,
        "lastSetValue": 5,
        "size": 1,
        "value": 5
      },
      {
        "id": 101,
        "lastReportedValue": 4,
        "lastSetValue": 4,
        "size": 4,
        "value": 4
      },
      {
        "id": 102,
        "lastReportedValue": 8,
        "lastSetValue": 8,
        "size": 4,
        "value": 8
      },
      {
        "id": 103,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 4,
        "value": 0
      },
      {
        "id": 111,
        "lastReportedValue": 3,
        "lastSetValue": 3,
        "size": 4,
        "value": 3
      },
      {
        "id": 112,
        "lastReportedValue": 600,
        "lastSetValue": 600,
        "size": 4,
        "value": 600
      },
      {
        "id": 113,
        "lastReportedValue": 600,
        "lastSetValue": 600,
        "size": 4,
        "value": 600
      },
      {
        "id": 120,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      },
      {
        "id": 2,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 2,
        "value": 0
      },
      {
        "id": 13,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      }
    ],
    "pollingTimeSec": 0,
    "zwaveCompany": "AEON Labs",
    "zwaveInfo": "3,3,40",
    "zwaveVersion": "1.15",
    "categories": [
      "lights"
    ],
    "configured": true,
    "dead": false,
    "deadReason": "",
    "deviceControlType": 23,
    "deviceIcon": 15,
    "endPointId": 0,
    "isLight": true,
    "log": "",
    "logTemp": "",
    "manufacturer": "",
    "markAsDead": true,
    "model": "",
    "nodeId": 15,
    "parametersTemplate": "202",
    "productInfo": "0,134,0,3,0,19,1,15",
    "saveLogs": true,
    "sceneActivation": 0,
    "serialNumber": "",
    "state": false,
    "switchAllMode": "",
    "useTemplate": true,
    "userDescription": "",
    "value": 0
  },
  "actions": {
    "getParameter": 1,
    "reconfigure": 0,
    "sceneActivationSet": 0,
    "setParameter": 2,
    "setValue": 1,
    "startLevelDecrease": 0,
    "startLevelIncrease": 0,
    "stopLevelChange": 0,
    "toggle": 0,
    "turnOff": 0,
    "turnOn": 0
  },
  "created": 1636542377,
  "modified": 1636542377,
  "sortOrder": 18
}

**Comment by alexander-vitishchenko** [comment]
"Device STUDY #144 (nil) identified as light-binary" - is it the same as what you see at your logs during QuickApp start up too? 

Then I can add Dimmer integration to support "AEON Labs Dimmable Switches" without having a physical device

**Comment by tvamvaki** [comment]
Thanks for the prompt response. Yes, I see the following:

[15.11.2021] [22:46:42] [DEBUG] [QUICKAPP145]: Device STUDY #144 (Master Bedroom) identified as light-binary

**Comment by alexander-vitishchenko** [comment]
@tvamvaki I've just updated QuickApp with a broader range of Dimmer devices support, which should cover AEON Labs.

Can you please test it and tell me if it works for you?

**Comment by alexander-vitishchenko** [comment]
@tvamvaki have you had a chance to check the new version of the QuickApp?

**Comment by tvamvaki** [comment]
Hi apologies for not getting back to you. I hadn’t had time to test it. 

I just tried it briefly today and from I can tell it works perfectly. I’ll do more testing over the next week and let you know how it all goes. 

Great work!
