### ISSUE TITLE
Unexpected response status Starting_Services

### ISSUE THREAD

**Issue by MomosX** [alexander-vitishchenko/hc3-to-mqtt#15]
Hi,

I have upgraded to the latest version and i have a lot of warnings in my log.

![image](https://user-images.githubusercontent.com/61582845/148894926-3e55413c-45c1-4e63-9ca2-a14b8f681d29.png)

Any idea where they come from please ?

**Comment by MomosX** [comment]
never mind:) it is gone.  the HC3 had a reboot...

**Comment by alexander-vitishchenko** [comment]
@MomosX 

Yes, it's fine for HC3 to report "STARTING_SERVICE" message during the reboot

I can tweak the warning message for a next release of the QuickApp so wording doesn't look as "unexpected" :-)

**Comment by MomosX** [comment]
what info from thermostats would you need to be able to implement them pls ?
I have danfoss LC13, Danfoss Room Sensor, Fibaro FGT001 and some more installed

**Comment by alexander-vitishchenko** [comment]
@MomosX I need JSON info about parent and child thermostat devices from Swagger UI, then I have a chance to add support for new devices

The best would be to send me devices over mail, then I can do both implementation and testing in one go, without making guesses and faster than making assumptions how devices work
