### ISSUE TITLE
Danfoss LC13 TRV Support

### ISSUE THREAD

**Issue by MomosX** [alexander-vitishchenko/hc3-to-mqtt#17]
I have attached the json files for Danfoss LC13 raditor heads.

Thank you 
[Danfoss-LC13.zip](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/7919894/Danfoss-LC13.zip)
!

**Comment by alexander-vitishchenko** [comment]
Hi @MomosX

Can you please prioritize what thermostats take the most priority for you, if choosing between Fibaro FGT-001, Danfoss LC13 TRV Support, and Danfoss RoomSensor Thermostat?

**Comment by MomosX** [comment]
same fix https://github.com/alexander-vitishchenko/hc3-to-mqtt/issues/31 but use "com.fibaro.thermostatDanfoss"

**Comment by alexander-vitishchenko** [comment]
Hi @MomosX - can you please check if the latest version of the QuickApp works for your thermostats?

**Comment by MomosX** [comment]
works only if i modify:

```
function Thermostat.isSupported(fibaroDevice)
    if (fibaroDevice.type == "com.fibaro.hvacSystem" or fibaroDevice.type == "com.fibaro.FGT001" or fibaroDevice.type == "com.fibaro.thermostatDanfoss") then 
        return true 
    else 
        return false
    end
end
```

**Comment by alexander-vitishchenko** [comment]
Hi @MomosX are you sure that you use the latest version of the QuickApp?

I've tested your device JSON locally and it was successfully identified as the thermostat.

![Screenshot 2023-01-08 230128](https://user-images.githubusercontent.com/1070777/211221214-8a0a7c07-06f3-47b6-a163-5030814856a0.png)

Can you please share your logs/screenshots?

**Comment by alexander-vitishchenko** [comment]
Hi @MomosX can you please advise if you are using the latest QuickApp version, and share full logs?

**Comment by alexander-vitishchenko** [comment]
Closed as expired, and need more inputs to confirm the issue exist and then fix it
