### ISSUE TITLE
Danfoss RoomSensor Thermostat support

### ISSUE THREAD

**Issue by MomosX** [alexander-vitishchenko/hc3-to-mqtt#18]
attached the files for Danfoss RoomSensor Thermostat.

Thank you !
[Danfoss-RoomSensor.zip](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/7919896/Danfoss-RoomSensor.zip)

**Comment by alexander-vitishchenko** [comment]
Hi @MomosX

Can you please prioritize what thermostats take the most priority for you, if choosing between Fibaro FGT-001, Danfoss LC13 TRV Support, and Danfoss RoomSensor Thermostat?

**Comment by MomosX** [comment]
same fix https://github.com/alexander-vitishchenko/hc3-to-mqtt/issues/31 but use "com.fibaro.thermostatDanfoss"

**Comment by alexander-vitishchenko** [comment]
Hi @MomosX - can you please check if the latest version of the QuickApp works for your thermostats?

**Comment by MomosX** [comment]
works only if i modify:

```
function Thermostat.isSupported(fibaroDevice)
    if (fibaroDevice.type == "com.fibaro.hvacSystem" or fibaroDevice.type == "com.fibaro.FGT001" or fibaroDevice.type == "com.fibaro.thermostatDanfoss") then 
        return true 
    else 
        return false
    end
end
```

**Comment by alexander-vitishchenko** [comment]
Hi @MomosX can you please advise if you are using the latest QuickApp version, and share full logs?

**Comment by alexander-vitishchenko** [comment]
Closed as expired, and need more inputs to confirm the issue exist and then fix it
