### ISSUE TITLE
Error while saving

### ISSUE THREAD

**Issue by dkcsn** [alexander-vitishchenko/hc3-to-mqtt#2]
I downloaded the new version - its corrupted or something else is wrong. When changing the variables - HC3 shows an error with red - "cannot save". Old version works. I tried download again /  - try all over, but i cant save/change the variables. actually i have never seen this error in HC3 before. [http://www.nyfodt.dk/downloads/Error%20while%20saving.jpg](url)

**Comment by alexander-vitishchenko** [comment]
Fibaro HC3 requires QuickApp variables to have non-empty value.

There are two options for you, depending how you want to pass user credentials (as plain text or base 64):
1. provide a proper value for mqttAuth
2. remove mqttAuth variable, and use mqttUsername and mqttPassword

**Comment by alexander-vitishchenko** [comment]
+ I'll probably remove mqttAuth, mqttUsername and mqttPassword variables from .fqa file, so people won't have to deal with them until it's needed

**Comment by alexander-vitishchenko** [comment]
I assume your issue if fixed, so I close the issue

By the way, QuickApp for a new version recently:
* FQA variables leverage non-empty values, so you won't hit the same issue again
* Able to pass Fibaro HC3 credentials in plain text form (not only Base64)
* Major codebase refactoring that uses modular structure for Device API and MQTT APIs, enabling the following benefits in a longer term:
   * add more device types support with less efforts
   * possibility to introduce Homio MQTT convention support
* QuickApp bootstrap and Fibaro HC3 events processing speed has been improved nearly by 30%
* I've probably introduced some bugs too :), as I had to rewrite almost half of the code, but I'll be doing extensive testing over the next few weeks, identify and eliminate defects
