### ISSUE TITLE
Battery level to HA

### ISSUE THREAD

**Issue by JeromeChignola** [alexander-vitishchenko/hc3-to-mqtt#20]
Hello Alexander. 
is there a way to get the battery levels from Zwave device like thermostat to HA? 
Jerome

**Comment by alexander-vitishchenko** [comment]
Yes, it should be possible to expose HC3 device battery level attribute as entity for Home Assistant

Just need time to get it implemented after adding support for new thermostat, e.g. Danfoss, POPP, Fibaro

**Comment by alexander-vitishchenko** [comment]
Hi @JeromeChignola

Please let me know if tracking battery level is still relevant for you?

And if so - can you please send me JSON files for all the parent+child entities from your HC3 thermostat? I assume each thermostat vendor may use it's own approach, so it would be great to have JSON files provided for Danfoss, POPP and Fibaro separately.

Thank you,
Alexander

P.S.: apologies for late reply as I only finished my accommodation in Berlin

**Comment by alexander-vitishchenko** [comment]
Hi @JeromeChignola,

Done, battery level sensors support has been introduced to Fibaro HC3 <-> Home Assistant

**Comment by alexander-vitishchenko** [comment]
@JeromeChignola by the way, please let me know if you know anyone who need help from smart home installers like me, especially if it's not far from Berlin :-)
