### ISSUE TITLE
control tilt position of venetion blinds with Fibaro FGR-223

### ISSUE THREAD

**Issue by jnorbi** [alexander-vitishchenko/hc3-to-mqtt#21]
Hi,

Could you check this and implement tilt position control of venetion blinds, please: https://github.com/zwave-js/zwavejs2mqtt/issues/971

Here is the forum link where I found the other one: https://community.home-assistant.io/t/fibaro-roller-shutter-3-fgr-223-lamellas-position-venetian-blind-tilt-position-is-not-working/97692/11

Thanks in advance,
Norbert

**Comment by alexander-vitishchenko** [comment]
Sure, I'll try to look at it once things go back to normal in Ukraine/Kyiv (hopefully). 

We have a war with russia who attacked Ukraine cowardly

**Comment by jnorbi** [comment]
Ohh no... I simply can't believe this situation :( I'm checking the news every 10 mins, but I never thought I'll have such a direct contact. Of course it's not the most important thing at the moment, but glad to see that you can still access internet. Stay safe, I hope this nightmare ends soon. I wish you all the best and peace!

**Comment by alexander-vitishchenko** [comment]
Hi @jnorbi 

Please let me know if tilt position control is still relevant for you?

And if so - can you please send me JSON files for your parent and child entities from your HC3 swagger?

Thank you,
Alexander

P.S.: apologies for late reply as I only finished my accommodation in Berlin

**Comment by jnorbi** [comment]
Hi @alexander-vitishchenko 

It's good to see that you are okay! :) yes, it would be really nice if I could control the venetian blinds via mqtt.

Well, until you were unavailabe I tried to read about this device and tried to figure out the possible solution.

The only trick this device has "value" and "value2" field and the "value2" filed is not a standard Z-Wave device field, it's a Fibaro special thing. The "value" filed is for the up/down position, the "value2" field is for the tilt position in venetian blind mode. I tried to edit the LUA files but without a good developer env it wasn't easy...

At the moment the roller shutter modules are paired with a Z-Wave JS, but I found a JSON here: https://github.com/ilcato/homebridge-Fibaro-HC2/issues/141

If you need anything else let me know and I'll try to send you ASAP.

Thanks in advance,
Norbert

**Comment by alexander-vitishchenko** [comment]
Hi @jnorbi,

This JSON https://github.com/ilcato/homebridge-Fibaro-HC2/issues/141 is about HC2, while we use HC3

They may use a similar structure, but better double-check as it should take only few minutes of your time, and much longer for me in case HC3 is different and then I'll have to rework the implementation :-)

Just clicking Swagger (left-bottom part of main Fibaro HC3 screen) => devices => GET
 /devices/{deviceID} => then share with me as a text file attached to GitHub response

Is all good about it?

**Comment by jnorbi** [comment]
Hi @alexander-vitishchenko,

Sure-sure :) at the moment I'm not at home, but I'll send you in a few days. I have to pair with HC3 one of the modules.

**Comment by alexander-vitishchenko** [comment]
Please let me know if the request is still relevant, or could be closed as outdated due to no inputs provided

**Comment by jnorbi** [comment]
Hi @alexander-vitishchenko ,

Sorry about the late reply, it's still relevant.

Here is the JSON from HC3:
response_1675154326793.json - the main device
response_1675154391851.json - roller shutter device (here you can see the "value2" value for the slats)
[json.zip](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/10544411/json.zip)

Thanks in advance!

Norbert

**Comment by Sukciukas** [comment]
[Roller shutter files.zip](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/11108501/Roller.shutter.files.zip)

Hello Alexander, attached files for fibaro roller shutter device. 
In fibaro i have device ID909 controlling venetian blinds with two slides : one for vertical up down position second one for slats opening and closing. 
in home assistant this device controls only vertical up down position, is it possible to add slats control - to have in home assistant in one card two slides for controlling vertical position and slats position. 

fibaro home center shows only ID 908 and ID909 devices other are hidden. I have unhide ID910 device, and named it \slats/ to check if it is possible to control slats in home assistant. when device was imported to HA i have two cards for one venetian blind allowing me control vertical position and slats but it is not comfortable to have two cards separately.

**Comment by alexander-vitishchenko** [comment]
Hi @jnorbi, @Sukciukas,

Please check the latest QuickApp version and let me know if it works for you?

**Comment by Sukciukas** [comment]
Hello @alexander-vitishchenko 

i have tested and can confirm that venetian blinds update works.
