### ISSUE TITLE
Qubino 3 Phase Smart Meter

### ISSUE THREAD

**Issue by Schelin78** [alexander-vitishchenko/hc3-to-mqtt#22]
Will get two switches in HA but no values ? See all values in HC3 but no one in HA
https://qubino.com/products/3-phase-smart-meter/

Config_entry_mqtt

    "id": "d5941b377db4de900811ac320ebd4dd0",
        "name": "773",
        "name_by_user": null,
        "disabled": false,
        "disabled_by": null,
        "entities": [
          {
            "device_class": null,
            "disabled_by": null,
            "disabled": false,
            "entity_category": null,
            "entity_id": "light.793_5_el_forbrukning",
            "icon": null,
            "original_device_class": null,
            "original_icon": null,
            "state": {
              "entity_id": "light.793_5_el_forbrukning",
              "state": "on",
              "attributes": {
                "supported_color_modes": [
                  "onoff"
                ],
                "color_mode": "onoff",
                "viewXml": false,
                "id": 937,
                "visible": true,
                "baseType": "com.fibaro.actor",
                "isPlugin": false,
                "configXml": false,
                "type": "com.fibaro.binarySwitch",
                "enabled": true,
                "interfaces": [
                  "light",
                  "zwave",
                  "zwaveMultiChannelAssociation"
                ],
                "roomID": 601,
                "sortOrder": 242,
                "modified": 1647163172,
                "parentId": 793,
                "created": 1647163172,
                "actions": {
                  "toggle": 0,
                  "turnOn": 0,
                  "turnOff": 0,
                  "reconfigure": 0
                },
                "properties": {
                  "logTemp": "",
                  "saveLogs": true,
                  "useTemplate": true,
                  "value": false,
                  "deadReason": "",
                  "userDescription": "",
                  "isLight": true,
                  "supportedDeviceRoles": [
                    "Light",
                    "Drencher",
                    "Pin",
                    "NightLamp",
                    "Kettle",
                    "Bracket",
                    "AirConditioner",
                    "AlarmAlarm",
                    "Coffee",
                    "GardenLamp",
                    "TvSet",
                    "CeilingFan",
                    "Toaster",
                    "Radio",
                    "RoofWindow",
                    "Other",
                    "AlarmState",
                    "AlarmArm",
                    "VideoGateBell",
                    "VideoGateOpen",
                    "Valve"
                  ],
                  "deviceIcon": 2,
                  "deviceRole": "Light",
                  "categories": [
                    "lights"
                  ],
                  "zwaveInfo": "3,4,61",
                  "dead": false,
                  "zwaveCompany": "Goap",
                  "zwaveVersion": "1.0",
                  "endPointId": 5,
                  "state": false,
                  "serialNumber": "",
                  "log": "",
                  "productInfo": "1,89,0,7,0,84,1,0",
                  "markAsDead": true,
                  "pollingTimeSec": 0,
                  "model": "",
                  "deviceControlType": 2,
                  "parametersTemplate": 847,
                  "nodeId": 97,
                  "manufacturer": "",
                  "configured": true
                },
                "view": [
                  {
                    "translatesPath": "/dynamic-plugins/com.fibaro.binarySwitch/i18n",
                    "assetsPath": "/dynamic-plugins/com.fibaro.binarySwitch/assets",
                    "name": "com.fibaro.binarySwitch",
                    "type": "ts",
                    "jsPath": "/dynamic-plugins/com.fibaro.binarySwitch"
                  }
                ],
                "friendly_name": "793.5 (El f\u00f6rbrukning)",
                "supported_features": 0
              },
              "last_changed": "2022-03-13T09:35:09.223818+00:00",
              "last_updated": "2022-03-13T09:35:09.223818+00:00"
            },
            "unit_of_measurement": null
          },
          {
            "device_class": null,
            "disabled_by": null,
            "disabled": false,
            "entity_category": null,
            "entity_id": "light.793_6_el_forbrukning",
            "icon": null,
            "original_device_class": null,
            "original_icon": null,
            "state": {
              "entity_id": "light.793_6_el_forbrukning",
              "state": "on",
              "attributes": {
                "supported_color_modes": [
                  "onoff"
                ],
                "color_mode": "onoff",
                "viewXml": false,
                "id": 938,
                "visible": true,
                "baseType": "com.fibaro.actor",
                "isPlugin": false,
                "configXml": false,
                "type": "com.fibaro.binarySwitch",
                "enabled": true,
                "interfaces": [
                  "light",
                  "zwave",
                  "zwaveMultiChannelAssociation"
                ],
                "roomID": 601,
                "sortOrder": 243,
                "modified": 1647163172,
                "parentId": 793,
                "created": 1647163172,
                "actions": {
                  "toggle": 0,
                  "turnOn": 0,
                  "turnOff": 0,
                  "reconfigure": 0
                },
                "properties": {
                  "logTemp": "",
                  "saveLogs": true,
                  "useTemplate": true,
                  "value": false,
                  "deadReason": "",
                  "userDescription": "",
                  "isLight": true,
                  "supportedDeviceRoles": [
                    "Light",
                    "Drencher",
                    "Pin",
                    "NightLamp",
                    "Kettle",
                    "Bracket",
                    "AirConditioner",
                    "AlarmAlarm",
                    "Coffee",
                    "GardenLamp",
                    "TvSet",
                    "CeilingFan",
                    "Toaster",
                    "Radio",
                    "RoofWindow",
                    "Other",
                    "AlarmState",
                    "AlarmArm",
                    "VideoGateBell",
                    "VideoGateOpen",
                    "Valve"
                  ],
                  "deviceIcon": 2,
                  "deviceRole": "Light",
                  "categories": [
                    "lights"
                  ],
                  "zwaveInfo": "3,4,61",
                  "dead": false,
                  "zwaveCompany": "Goap",
                  "zwaveVersion": "1.0",
                  "endPointId": 6,
                  "state": false,
                  "serialNumber": "",
                  "log": "",
                  "productInfo": "1,89,0,7,0,84,1,0",
                  "markAsDead": true,
                  "pollingTimeSec": 0,
                  "model": "",
                  "deviceControlType": 2,
                  "parametersTemplate": 847,
                  "nodeId": 97,
                  "manufacturer": "",
                  "configured": true
                },
                "view": [
                  {
                    "translatesPath": "/dynamic-plugins/com.fibaro.binarySwitch/i18n",
                    "assetsPath": "/dynamic-plugins/com.fibaro.binarySwitch/assets",
                    "name": "com.fibaro.binarySwitch",
                    "type": "ts",
                    "jsPath": "/dynamic-plugins/com.fibaro.binarySwitch"
                  }
                ],
                "friendly_name": "793.6 (El f\u00f6rbrukning)",
                "supported_features": 0
              },
              "last_changed": "2022-03-13T09:35:10.206376+00:00",
              "last_updated": "2022-03-13T09:35:10.206376+00:00"
            },
            "unit_of_measurement": null
          }
        ]
      }
    ],

**Comment by alexander-vitishchenko** [comment]
Hi @Schelin78 

Let me try to have a look at it.

FYI - I had to move to Berlin from Kyiv (Ukraine) recently and need to accommodate at a new place, which is not that easy as I thought initially

**Comment by drzordz** [comment]
Hi I have problem too with this qubino. I have many devices from Fibaro HC3 but I don't see anything qubino in my HA.

**Comment by Schelin78** [comment]
Hi, found that it works with HA fibaro solution.

Hope you winn this war soon

Best regards Daniel

Den sön 27 mars 2022 09:45drzordz ***@***.***> skrev:

**Comment by alexander-vitishchenko** [comment]
Hi @Schelin78, @drzordz,

Can you please advise whether the issue persist, or resolved?

Thank you,
Alexander

P.S.: apologies for late reply as I only finished my accommodation in Berlin

**Comment by alexander-vitishchenko** [comment]
Assume that the issues is resolved due to the latest comment above + closing the issue due to its expiration.

Please let me know if you need any further assistance.
