### ISSUE TITLE
Juste question for potential feature - Send mqtt every x min

### ISSUE THREAD

**Issue by adetauriac** [alexander-vitishchenko/hc3-to-mqtt#26]
Hello,

 Your QuickApp is very interresting and I use it since several week/month to load in Influxdb some data.
But I've some device without lot of update, like Internet box, where power is very stable, or some other device when they are off... and if understand, no new mqtt message if no update.

But when I try to have grap (grafana), without data, it's complicated to have correct interface.
I would like to know if it's possible to have process to have regulare message, without wait update of device. I see 2 solutions, but not sure if I've capacity to implemente them :
  - Have process to rescan and sent mqtt message every x min
  - QA subcribe to topic mqtt, an when message is recieved, new scan is done 

What to you think of this feature ? 

 Thanks

**Comment by alexander-vitishchenko** [comment]
Hi @adetauriac!

Yes it is possible to do.

Let me recap how I understood you, and you tell me if this is correct:

- QuickApp is started, doing initial HC3 device scan, then publish device state/values to MQTT
- QuickApp is constantly monitoring HC3 events to see if any device got their state/values changed, and then publishes it to MQTT
- If no device state/value changes detected - nothing is published to Home Assistant via MQTT... and then you tell Grafana has issues to render charts properly?

Few questions:
1. Does the same kind of Grafana issue occur for native Home Assistant devices, which are not sourced from HC3 via MQTT? If Grafana struggles to deal with lack of device state/values updates - then maybe the proper approach would be to do rescans for all Home Asisstant devices, not only those sourced by HC3 via MQTT, right? Plus worth contacting Grafana developers to do if they can improve the implementation for pretty normal situations when devices have no state/value changes
2. If this is only relevant HC3/MQTT... then what about implementing HC3 scene that "restarts" QuickApp, let's say every midnight? HC3 has a nice UI to schedule timers, and restarting QuickApp is absolutely normal process that will trigger rescan and sending all the device state/values to MQTT. Such approach looks a bit more user-friendly, and let you decide how often to do the rescan, without reimplementing the existing scheduler functionality.

Would it work for you?

Thank you,
Alexander

P.S.: apologies for late reply as I only finished my accommodation in Berlin

**Comment by alexander-vitishchenko** [comment]
Closing the issue as no further inputs provided, and because there an alternative solution ;-) with an architectural design that looks cleaner by not making scheduler logic reimplemented within the QuickApp, and already available at Fibaro HC3
