### ISSUE TITLE
[Feature] Implement Mqtt standard specification

### ISSUE THREAD

**Issue by slobberbone** [alexander-vitishchenko/hc3-to-mqtt#3]
It would be interesting to implement in this project the specification describe here :
https://homieiot.github.io/

However, MQTT doesn’t define the structure and content of these messages and their relation. An IoT device publishes data and provides interaction possibilities but a controlling entity will need to be specifically configured to be able to interface with the device.

The Homie convention defines a standardized way of how IoT devices and services announce themselves and their data on the MQTT broker.

It is thereby a crucial aspect on top of the MQTT protocol for automatic discovery, configuration and usage of devices and services.

Some other xxx2mqtt already purpose this and I think specification for MQTT is the futur of home automation.
It would be not changing the way of this project work actually, but add another way to publish.

I'm from the open source project NextDom (home automation software) and we are working on another solution from scratch. We want to organize NextDom directly with MQTT and Node-Red (Nextdom becoming a kind of orchestrator. In this way, this standard for MQTT will be very interesting for us of course, but also for all others home automation software.

Thanks for reading and give me some feed back about that !

**Comment by alexander-vitishchenko** [comment]
Hi @slobberbone!

I like the spec and the idea behind it.

Can you please advise on the few questions before we jump into discussing implementation details and timelines?
* have you considered Home Assistant MQTT convention as an alternative? This may be not an industry standard, but many people use it de-facto. Home Assistant is able to push your devices further to HomeKit, and then you can control your smart home with voice using Apple Watch, AirPods/iPhone, etc... which is nice bonus to have with almost zero additional efforts :)
* do we have any kind of understanding how many smart home installations may benefit from Fibaro HC3 <-> Homie MQTT convention for Q1-Q2 2021? Just some rough figures so I can prioritise the work for March or later months, depending how many people need it :)

**Comment by slobberbone** [comment]
Thank you for your interest !
I know Home Assistant cenvention, but it's not a really true standard. My interest is to come back some interoperability in home automation ...
I don't know how many HC3 to mqtt exists and how many with homie but it's not my point here. To be honest I don't use Homie at all, but I'm interest by a standard something in common and well thinking .... the Home automation stuff is not very good and whereas to have a boolean for HA compliant, then another to another home automation software, it's better to respect a standard, this one (and it's pretty well done) at the end the goal is HA use this standard too because all don't turn around HA ;)
I'm from the NextDom community and we start from scratch to devvelop a new solution for home automation but we are more like an orchestrator between MQTT, Node-Red , an API and finaly an UI but we can be compliant with Domoticz, or HA or OpenHAB, becasue at the end we respect a standard the Homie one ... I hope you understand my point :)

**Comment by alexander-vitishchenko** [comment]
Let me see what I can do about it over weekend

**Comment by alexander-vitishchenko** [comment]
And so by doing a bit of analysis, it feels like the implementation should be ready in few weeks time. 

The efforts come from:
* refactor the codebase and separate "MQTT conventions" related logic from other other functions (e.g. HC3, core specific). This will improve the codebase maintainability by implementing some of the [SOLID principles](https://en.wikipedia.org/wiki/SOLID), and thus establish a healthy foundation for expanding the QuickApp with more features in a future by avoiding Spaghetti code
* add new QuickApp variables, to let users set which conventions they like to use, e.g. "Only Home Assistant", "Only Homie", "Home Assistant + Homie"
* implement Homie convention itself

**Comment by alexander-vitishchenko** [comment]
I've recently committed a new QuickApp version that leverages a modular structure for (a) Device API (b) MQTT Convention API:
* this will simplify QuickApp extension with new features, and help to maintain a better functional quality in a long term
* improved bootstrap and events processing performance by nearly 30%

No Homio support yet... but all the preparations are done, which is roughly about 1/2 of the overall work. @slobberbone can you please clarify if you still need it? If not - then I'm planning to implement support for most basic Homio properties/attributes/commands only :)

**Comment by slobberbone** [comment]
Hy @alexander-vitishchenko Thanks for your work and interest ;) We are still interest to have more and more project respecting this specification made by Homie. We are working a lot on our NextDom solution and in few time we will dev the adapter to Homie standard (and HA because these are the 2 standards for now).

**Comment by alexander-vitishchenko** [comment]
@slobberbone I've just submitted the initial implementation for "Homie" MQTT convention, including support for property read and set operations

1. It needs to be enabled with QuickApp variable "mqttConvention" = "homie"
![image](https://user-images.githubusercontent.com/1070777/109720918-617ee280-7bb3-11eb-91c3-146ff223485d.png)
2. I had no possibilities to test so far... do I need to install NextDom? :) Not sure if this is an easy thing to do, and perhaps you can do a bit of the initial testing by yourself and see if I'm moving to the right direction
3. I could be wrong here, but it looks like Homie convention doesn't specify how "rooms" to be handled exactly... the spec seems to be "all purpose" IoT convention. So we need to make design decision by ourselves, for exposing rooms to the MQTT topic hierarchy
