### ISSUE TITLE
Device of type com.fibaro.FGT001

### ISSUE THREAD

**Issue by dani2dani** [alexander-vitishchenko/hc3-to-mqtt#31]
Hi,

I really very appreciate your work it is very helpful for my integration of Fibaro to Home Assistant.

I have a small improvement for the [Fibaro Heat Controller](https://manuals.fibaro.com/heat-controller/)

If I add

```
function Thermostat.isSupported(fibaroDevice)
    if (fibaroDevice.type == "com.fibaro.hvacSystem" or **fibaroDevice.type == "com.fibaro.FGT001"**) then 
        return true 
    else 
        return false
    end
end
```

it is working without any issues.

Cheers

D.

**Comment by alexander-vitishchenko** [comment]
Hi @dani2dani 

1) Yes, HVAC devices may have multiple type aliases in HC3 ecosystem. For some reason, this is especially valid for Z-Wave devices that are manufactured by Fibaro - they may use custom device types like FGT001 or BFG3000 =), and it could be hardly predetermined by a fixed pattern upfront.

This is why device_api.lua contains custom type alias mappings at "fibaroBaseTypeOverride" and "fibaroTypeOverride". All we have to do is to add a new row like ["com.fibaro.FGT001"] = "com.fibaro.hvacSystem". I can do it for you, just let me see your HVAC device info in JSON format.

2) The ideal solution would be to make Z-Wave device manufacturers stick to a common device typing approach... but we all know it make take ages to get implemented =) Therefore need to rely on temporary (hopefully) solutions like mappings above, and probably not investing much efforts into something what is supposed to be a mere workaround.

Introducing wildcards to custom alias mappings could mitigate the issue with Z-Wave device type mappings... but still no 100% guarantee.

Thank you,
Alexander

P.S.: apologies for late reply as I only finished my accommodation in Berlin

**Comment by dani2dani** [comment]
Thx for explanation.
