### ISSUE TITLE
Aeotec siren 6 in mqtt

### ISSUE THREAD

**Issue by leffrh** [alexander-vitishchenko/hc3-to-mqtt#32]
Hi Alexander,

do you think you can add the siren 6?

In the logs i get:

[27.10.2022] [10:08:08] [DEBUG] [QUICKAPP732]: Couldn't recognize device #350 - Sirene - com.fibaro.actor - com.fibaro.soundSwitch
[27.10.2022] [10:08:08] [DEBUG] [QUICKAPP732]: Couldn't recognize device #351 - Inbraak_Alarm - com.fibaro.actor - com.fibaro.soundSwitch
[27.10.2022] [10:08:08] [DEBUG] [QUICKAPP732]: Couldn't recognize device #352 - Deurbel - com.fibaro.actor - com.fibaro.soundSwitch
[27.10.2022] [10:08:08] [DEBUG] [QUICKAPP732]: Couldn't recognize device #353 - 348.4 - com.fibaro.actor - com.fibaro.soundSwitch
[27.10.2022] [10:08:08] [DEBUG] [QUICKAPP732]: Couldn't recognize device #354 - 348.5 - com.fibaro.actor - com.fibaro.soundSwitch
[27.10.2022] [10:08:08] [DEBUG] [QUICKAPP732]: Couldn't recognize device #355 - Smoke_Alarm - com.fibaro.actor - com.fibaro.soundSwitch
[27.10.2022] [10:08:08] [DEBUG] [QUICKAPP732]: Couldn't recognize device #356 - Brandalarm - com.fibaro.actor - com.fibaro.soundSwitch
[27.10.2022] [10:08:08] [DEBUG] [QUICKAPP732]: Couldn't recognize device #357 - 348.8 - com.fibaro.actor - com.fibaro.soundSwitch
[27.10.2022] [10:08:08] [DEBUG] [QUICKAPP732]: Couldn't recognize device #361 - Home - com.fibaro.device - com.fibaro.genericDevice

https://aeotec.com/products/aeotec-siren-6/

Thanks

Roelof

**Comment by alexander-vitishchenko** [comment]
hi @leffrh,

Can you please share your device in JSON format? You can extract it from your Fibaro HC3 => Swagger (in the top-left part of the screen) => Devices => Get device by id

Thank you,
Alexander

**Comment by leffrh** [comment]
Like this :

{
  "id": 352,
  "name": "Deurbel",
  "roomID": 227,
  "view": [
    {
      "assetsPath": "dynamic-plugins/com.fibaro.soundSwitch",
      "name": "com.fibaro.soundSwitch",
      "translatesPath": "/assets/i18n/com.fibaro.soundSwitch",
      "type": "ts"
    }
  ],
  "type": "com.fibaro.soundSwitch",
  "baseType": "com.fibaro.actor",
  "enabled": true,
  "visible": true,
  "isPlugin": false,
  "parentId": 348,
  "viewXml": false,
  "hasUIView": false,
  "configXml": false,
  "interfaces": [
    "zwave",
    "zwaveAlarm",
    "zwaveMultiChannelAssociation"
  ],
  "properties": {
    "parameters": [
      {
        "id": 1,
        "lastReportedValue": 16777216,
        "lastSetValue": 16777216,
        "size": 4,
        "value": 16777216
      },

**Comment by alexander-vitishchenko** [comment]
Hi @leffrh 

I think I can implement it this weekend.

Do I understand your use-case correctly => you want to activate Aeotec Siren 6 based on your Home Assistant events? And you do not use Aeotec Siren 6 as a sensor, correct?

**Comment by leffrh** [comment]
Hi,

no rush :)
I want to use it as a trigger. It send a message to my mqtt server from my HomeCenter 3. From there i will pick up and activate some scenes from my homey.

**Comment by alexander-vitishchenko** [comment]
Hi @leffrh,

Apologies, just realized that you shared the trimmed version of your device info. Can you share the full JSON, ideally in a form of txt file attached? I need it to finalize the implementation for Aeotec Siren 6, by understand all supported properties, like siren tones, etc

**Comment by leffrh** [comment]
Hi,
hereby the file.
Let me know if you need more.

[1 output.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/9951771/1.output.txt)

**Comment by alexander-vitishchenko** [comment]
Hi @leffrh,

It looks like you provided JSON for a different hidden device 348. This might be handy at the later stage, but the current focus is to get Aeotec Siren 6 support enabled, using those device ids that are marked in logs as "Couldn't recognize device"

Need you to provide JSON for id 352, like you asked initially. Ideally for all the devices marked as "Couldn't recognize device" in logs.

**Comment by leffrh** [comment]
> Hi @leffrh,
> 
> It looks like you provided JSON for a different hidden device 348. This might be handy at the later stage, but the current focus is to get Aeotec Siren 6 support enabled, using those device ids that are marked in logs as "Couldn't recognize device"
> 
> Need you to provide JSON for id 352, like you asked initially. Ideally for all the devices marked as "Couldn't recognize device" in logs.

Hope this is what you need :)
[json response_1668417329133.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/10001477/json.response_1668417329133.txt)

Thanks

**Comment by alexander-vitishchenko** [comment]
This looks correct :-)

I've checked the device specification, and it appears to be more complicated than a regular switch or dimmer, and has the following properties expose tone/default tone, volume, state.

I need to understand what values are supported by each property, and it would be great if you could share few screenshots of the device preview screen, and also how the device properties are visualised at the Scene Editor?

**Comment by alexander-vitishchenko** [comment]
Hi @leffrh ,

I'm working on the task board priority actualisation, and also revising which tasks to remain open and which ones to be closed due to expiration.

Please let me know if your request is still relevant.

**Comment by Sukciukas** [comment]
Is there any chance that this device will be added ?

**Comment by alexander-vitishchenko** [comment]
Hi @Sukciukas 

I'll make another attempt this weekend and may possibly need more inputs from you.

And just to make sure I'm gonna be working on the right thing:
- Can you please share screenshots of your Aeotec Siren device at Fibaro UI (how you read its data or put it in a certain state)? 
- Can you please share your JSON device info from Swagger UI? 
- How do you plan to use Aeotec Siren at Home Assistant, few examples?

**Comment by Sukciukas** [comment]
Hello, 

i am not good at it so not sure how to get the info you need. 
in fibaro just created few scenes with it as main doors opens it makes sound. and another one is for night security if there is any breach in door or windows sensor it makes siren. 
in home assistant would like to use same way as a sound device.
have transfered all fibaro devices to home assistant but not created anything there at the moment.  
can you please tell me how to get those files you need so i could do it. thank you

**Comment by alexander-vitishchenko** [comment]
Here go the instructions from the GitHub project home screen


![image](https://user-images.githubusercontent.com/1070777/227468428-35243e2c-63ea-4e40-b179-3a2c916f918e.png)

**Comment by Sukciukas** [comment]
[Aeotec siren.zip](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/11060135/Aeotec.siren.zip)

attached zip with files.

**Comment by Sukciukas** [comment]
Sorry, as I said not sure what I am doing but quickly learning. please find ID240 device file the previous I have sent is incorrect. but screens are ok. 
[ID240.zip](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/11060201/ID240.zip)

**Comment by alexander-vitishchenko** [comment]
Now I see it much better! + need to have JSON files for all the child devices like 241, 242 as it is them to be used to trigger sound alarm

**Comment by Sukciukas** [comment]
attached ID240 parent + all child devices ID241-ID249
[Siren.zip](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/11060457/Siren.zip)

**Comment by alexander-vitishchenko** [comment]
Hi @leffrh, @Sukciukas,

Can you please check the latest version of the QuickApp and let me know if it works for you?

**Comment by Sukciukas** [comment]
it has imported siren to home assistant. showing it as switch, when turning on sound is active. some print screens if you need it added. 
![siren switch2](https://user-images.githubusercontent.com/106014840/228538710-571620a4-2e18-4fea-b3c9-0c72843a79b9.jpg)
![siren switch](https://user-images.githubusercontent.com/106014840/228538719-dea17b75-a1c0-4e2a-b9e4-b89d89682ba5.jpg)

**Comment by alexander-vitishchenko** [comment]
Hi @Sukciukas,

1. It's fine to remove the old QuickApp and then install the newer version.

The alternatives are:
- copy *.lua files from the new version of the QuickApp to your existing one, this might take extra time to do for each file, but no need to reconfigure QuickApp variables and QuickApp will keep using the same id (in case it is important to you)
- consider creating "Installer" in the future, but I'm not sure if it worth the effort at the current scale. Maybe I'll do it if there are at least 5+ users who confirm the intention to invest into it

2. Yes, Fibaro's "sound switch" is represented as a "switch" at Home Assistant. You turn it on when needed, and turn it off afterwards. You can use automations to enable the sound for fixed duration of <X> seconds

Does it work like you would expect?

**Comment by alexander-vitishchenko** [comment]
Hi @Sukciukas,

Please let me know if the new functionality works as expected and we can close the ticket?

**Comment by alexander-vitishchenko** [comment]
Closed as implementation is complete, with no more inputs provided by requestors
