### ISSUE TITLE
feat request : nice blinder support

### ISSUE THREAD

**Issue by ka2er** [alexander-vitishchenko/hc3-to-mqtt#36]
Hi I have Nice blinder.
I could try to add support just need some guidelines.

I would like to be able to use Yubii Home as mqtt gateway, send order from HASS via mqtt in order to open and close blinder.

Do you have some kind of "add device support" guideline documentation ?

**Comment by alexander-vitishchenko** [comment]
Hi @ka2er 

Happy to help. I have my home lab with Z-Wave devices and Nice is new to me, even Fibaro device signatures are supposed to be the same.

Can you send me device JSON info so I estimate the effort for new device type support implementation?

**Comment by ka2er** [comment]
As published into mqtt ?

**Comment by alexander-vitishchenko** [comment]
It is a bit simple, open Fibaro HC3 user interface, click at "Swagger" icon at the top-bottom part

<img width="58" alt="image" src="https://user-images.githubusercontent.com/1070777/208473869-e91ed3e6-450a-44c8-8877-2b2cffd448a4.png">

Then select "devices" from the dropdown list => enter your device id and share with me the resulting JSON

**Comment by ka2er** [comment]
`{
  "id": 34,
  "name": "VR baie vitrée",
  "roomID": 221,
  "view": [
    {
      "assetsPath": "dynamic-plugins/com.fibaro.remoteBaseShutter",
      "name": "com.fibaro.remoteBaseShutter",
      "translatesPath": "/assets/i18n/com.fibaro.remoteBaseShutter",
      "type": "ts"
    },
    {
      "assetsPath": "dynamic-plugins/favorite-positions",
      "name": "favorite-positions",
      "translatesPath": "/assets/i18n/favorite-positions",
      "type": "ts"
    }
  ],
  "type": "com.fibaro.remoteBaseShutter",
  "baseType": "com.fibaro.remoteController",
  "enabled": true,
  "visible": true,
  "isPlugin": false,
  "parentId": 46,
  "viewXml": false,
  "hasUIView": true,
  "configXml": false,
  "interfaces": [
    "favoritePosition",
    "nice",
    "niceMono"
  ],
  "properties": {
    "buttonHold": 5000,
    "categories": [
      "remotes"
    ],
    "configuration": true,
    "dead": false,
    "deadReason": "",
    "deviceControlType": 53,
    "deviceIcon": 218,
    "deviceRole": "BlindsWithoutPositioning",
    "deviceState": "Configured",
    "favoritePositions": [
      {
        "label": "Favorite position 1",
        "name": "FavoritePosition1",
        "value": 50
      }
    ],
    "favoritePositionsNativeSupport": true,
    "icon": {
      "path": "/assets/icon/fibaro/com.fibaro.remoteBaseShutter_garage/com.fibaro.remoteBaseShutter_garage.png",
      "source": "HC"
    },
    "inputToChannelMap": {
      "close": [
        3
      ],
      "open": [
        1
      ],
      "partialOpen1": [],
      "step": [],
      "stop": [
        2
      ],
      "toggleCh1": [],
      "toggleCh2": [],
      "turnOffCh1": [],
      "turnOffCh2": [],
      "turnOnCh1": [],
      "turnOnCh2": [],
      "unsupported": []
    },
    "log": "",
    "logTemp": "",
    "manufacturer": "NICE",
    "model": "",
    "niceId": 13,
    "niceProtocol": "Opera0",
    "numberOfSupportedButtons": 8,
    "saveLogs": true,
    "supportedDeviceRoles": [
      "BlindsWithoutPositioning",
      "VenetianBlinds",
      "Awning"
    ],
    "userDescription": ""
  },
  "actions": {
    "close": 0,
    "open": 0,
    "setFavoritePosition": 1,
    "stop": 0
  },
  "created": 1649487581,
  "modified": 1671310429,
  "sortOrder": 15
}`

**Comment by ka2er** [comment]
```
{
  "id": 34,
  "name": "VR baie vitrée",
  "roomID": 221,
  "view": [
    {
      "assetsPath": "dynamic-plugins/com.fibaro.remoteBaseShutter",
      "name": "com.fibaro.remoteBaseShutter",
      "translatesPath": "/assets/i18n/com.fibaro.remoteBaseShutter",
      "type": "ts"
    },
    {
      "assetsPath": "dynamic-plugins/favorite-positions",
      "name": "favorite-positions",
      "translatesPath": "/assets/i18n/favorite-positions",
      "type": "ts"
    }
  ],
  "type": "com.fibaro.remoteBaseShutter",
  "baseType": "com.fibaro.remoteController",
  "enabled": true,
  "visible": true,
  "isPlugin": false,
  "parentId": 46,
  "viewXml": false,
  "hasUIView": true,
  "configXml": false,
  "interfaces": [
    "favoritePosition",
    "nice",
    "niceMono"
  ],
  "properties": {
    "buttonHold": 5000,
    "categories": [
      "remotes"
    ],
    "configuration": true,
    "dead": false,
    "deadReason": "",
    "deviceControlType": 53,
    "deviceIcon": 218,
    "deviceRole": "BlindsWithoutPositioning",
    "deviceState": "Configured",
    "favoritePositions": [
      {
        "label": "Favorite position 1",
        "name": "FavoritePosition1",
        "value": 50
      }
    ],
    "favoritePositionsNativeSupport": true,
    "icon": {
      "path": "/assets/icon/fibaro/com.fibaro.remoteBaseShutter_garage/com.fibaro.remoteBaseShutter_garage.png",
      "source": "HC"
    },
    "inputToChannelMap": {
      "close": [
        3
      ],
      "open": [
        1
      ],
      "partialOpen1": [],
      "step": [],
      "stop": [
        2
      ],
      "toggleCh1": [],
      "toggleCh2": [],
      "turnOffCh1": [],
      "turnOffCh2": [],
      "turnOnCh1": [],
      "turnOnCh2": [],
      "unsupported": []
    },
    "log": "",
    "logTemp": "",
    "manufacturer": "NICE",
    "model": "",
    "niceId": 13,
    "niceProtocol": "Opera0",
    "numberOfSupportedButtons": 8,
    "saveLogs": true,
    "supportedDeviceRoles": [
      "BlindsWithoutPositioning",
      "VenetianBlinds",
      "Awning"
    ],
    "userDescription": ""
  },
  "actions": {
    "close": 0,
    "open": 0,
    "setFavoritePosition": 1,
    "stop": 0
  },
  "created": 1649487581,
  "modified": 1671310429,
  "sortOrder": 15
}```

**Comment by alexander-vitishchenko** [comment]
Interesting, this differs from Fibaro Z-Wave shutters.

Can you please also share few screenshots from Fibaro HC3 UI, showing what properties and actions are available for you?

**Comment by alexander-vitishchenko** [comment]
Hi @ka2er 

Please let me know if you request is still relevant, or it could be closed as no inputs/screenshots provided?

**Comment by ka2er** [comment]
sorry I had forgotten ... my bad :/

<img width="1499" alt="image" src="https://user-images.githubusercontent.com/126727/210649332-52a2de0b-750d-4eb8-a8f5-d3e0e838f118.png">

<img width="1499" alt="image" src="https://user-images.githubusercontent.com/126727/210649369-419ae56e-92ae-49f2-9e2a-b89595d32f94.png">

<img width="1499" alt="image" src="https://user-images.githubusercontent.com/126727/210649414-31d596df-d4fc-4f4c-ba88-7c3a112f6737.png">

<img width="1499" alt="image" src="https://user-images.githubusercontent.com/126727/210649442-997a8397-c924-4b71-a391-080a23f44e28.png">

Do you need screenshot of another UI parts ?

**Comment by ka2er** [comment]
<img width="1491" alt="image" src="https://user-images.githubusercontent.com/126727/210649552-2692f958-752f-46d4-a808-fb4735541cdc.png">

**Comment by alexander-vitishchenko** [comment]
Thanks @ka2er - this is very useful!

Can you please additionally send me JSON file for device #46, which is indicated as a parent for your blinder #34?

I'll see if I can release a new version of the QuickApp tomorrow, along with other updates accumulated over the last few weeks.

**Comment by ka2er** [comment]
```
{
  "id": 46,
  "name": "VR baie vitrée",
  "roomID": 221,
  "view": [],
  "type": "com.fibaro.device",
  "baseType": "",
  "enabled": true,
  "visible": false,
  "isPlugin": false,
  "parentId": 7,
  "viewXml": false,
  "hasUIView": false,
  "configXml": false,
  "interfaces": [
    "nice",
    "niceMono"
  ],
  "properties": {
    "buttonHold": 5000,
    "categories": [
      "other"
    ],
    "configuration": true,
    "dead": false,
    "deadReason": "",
    "deviceControlType": 1,
    "deviceIcon": 28,
    "deviceRole": "Other",
    "deviceState": "Configured",
    "icon": {},
    "inputToChannelMap": {},
    "log": "",
    "logTemp": "",
    "manufacturer": "NICE",
    "model": "",
    "niceId": 13,
    "niceProtocol": "Opera0",
    "numberOfSupportedButtons": 8,
    "saveLogs": true,
    "supportedDeviceRoles": [
      "Other"
    ],
    "userDescription": ""
  },
  "actions": {},
  "created": 0,
  "modified": 1671310430,
  "sortOrder": 23
}
```

**Comment by alexander-vitishchenko** [comment]
This was quick. Thanks and I'll let you know if I need more information.

**Comment by alexander-vitishchenko** [comment]
@ka2er I've added experimental Nice shutter support to the latest release, can you please check it out?

It should theoretically support other types of Nice devices, and Zigbee, if you have it for testing in your environment?

**Comment by alexander-vitishchenko** [comment]
Hi @ka2er,

Please let me know if the request is still relevant or should be closed?

**Comment by ka2er** [comment]
Hi, it works : well done!!
I successfully open / close / stop my shutter from Haas. Thanks !
does the PayPal Donate is still revelant ?

**Comment by alexander-vitishchenko** [comment]
Hi @ka2er,

Donates are always relevant :-) and it's up to you to decide how much you appreciate the work done.

Thank you,
Alexander
