### ISSUE TITLE
Problem in dispatchFibaroEventToMqtt(event) if a scene has the same identifier as a device

### ISSUE THREAD

**Issue by rico0260** [alexander-vitishchenko/hc3-to-mqtt#39]
Hello and I wish you a happy end of the year,
I send you this message to inform you of a problem:

The devices and a scene in question (I specify that for the moment only 5 floodSensors are exported to Home Assistant, and therefore no motionSensor or other device)

1 floodSensor (id 142)
1 Scene (id 142)
1 motionSensor (id 175)

My explanation, which I hope is clear:

In my case, the motionSensor (#175) triggers a scene (#142) to turn on a socket for a while (it works fine for a long time with a scene).

The floodSensor is waiting for him to report a leak. (no problem with the leak sensor)

But here I have the impression and even the certainty that the event triggered by the scenario #142 and understood for an event of the floodSensor #142.

I think you should make changes in the function : dispatchFibaroEventToMqtt(event)

Attached is a screenshot of the last log.

![image](https://user-images.githubusercontent.com/12649196/210157030-4bb76a43-d249-490b-9071-c5cce36ea419.png)

Best regards.

**Comment by alexander-vitishchenko** [comment]
Hi @rico0260 

Do you have your scene/automation set on Fibaro HC3 or Home Assistant?

QuickApp has no impact how your scene works on Fibaro HC3, but I'm happy to help.

If this is on HC3 side - can you send me your scene screenshots, and also it's copy in Lua format, so I can see what might be needed to get fix?

**Comment by rico0260** [comment]
Hello Alexander Vitishchenko, 
Yes my scene is configured in HC3,

Yes, I observed that the QuickApp has no impact on the scene, but the QuickApp intercepts the scene and takes it for an event of a floodSensor device which has the same ID (#142) automatically defined in the box HC3.

Attached the configuration of the scene:
![image](https://user-images.githubusercontent.com/12649196/210176329-5cf23c0c-3821-4955-832c-4e74d216b22a.png)

the same scene converted to Lua code:
![image](https://user-images.githubusercontent.com/12649196/210176363-29ed88cc-855f-4651-bf8e-263ce79229d4.png)

Best regards.

**Comment by rico0260** [comment]
Hello Alexander Vitishchenko,

I think we should check the origin of the event because in my case it is not from a device but from a scene:
![image](https://user-images.githubusercontent.com/12649196/210182618-bedd1814-0855-426a-b4a0-d98204652af9.png)

Always available to help.

Best regards.

**Comment by MomosX** [comment]
If i understand correctly this is not an issue, but an extra log line in the QA about some event.  If that's the case, it is not the only event that gets captured by the QA, as it should. You can safely ignore those log lines.

**Comment by rico0260** [comment]
A scene is not a device, so I made a pull request to inform the author of my modification.

Have a good year.

**Comment by alexander-vitishchenko** [comment]
Absolutely, I'll adjust the logging in a way it produces more relevant text messages for QuickApp users. There several places like this, including but not limited to scene-related events.

The initial intention was to capture any anomaly in the logs using "the more the better" approach, but without spending much time out refining the text. Luckily it is possible to do better now and the focus is to improve usability and long-term stability.
