### ISSUE TITLE
Fibaro Thermostats support

### ISSUE THREAD

**Issue by dmit2k** [alexander-vitishchenko/hc3-to-mqtt#4]
Thank you very much for this nice piece of code!

It works just fine with my HCL3 controller and connected sensors and relays, but I can't get the thermostatic heads to be recognised in full by HomeAssistant. 

I'm seeing only current temperature from it's sensors, but not the heating mode and heating setpoints.

Is it a bug or it is not implemented yet?

**Comment by alexander-vitishchenko** [comment]
hc3-to-mqtt bridge has "heat" and "cool" modes support, for the following thermostat models:
- Qubino On/Off Thermostat 2
- Connect Home CH-201/CH-202
- theoretically, any thermostat should work, with 3 preconditions (a) thermostat device is recognized by HC3/HCL3 (b) thermostat mode signatures match Home Assistant dictionary (c) temperature_sensor_id = thermostat_id + [1 or 2] 

There is a high chance that your Fibaro Thermostat doesn't match criteria (b) and/or (c). And if so - it should be real simple to add support for your device... if I only had it in my home lab.

As an option, you can **share your parent + child devices info**, in a form of JSON. Then I publish a new version of hc3-to-mqtt bridge that should support Fibaro Thermostat. 

fyi - you can get device info in a form of JSON using Swagger UI within HC3/HCL3info, or by using REST API http://<your HC3 server>/api/devices/<device_id>

**Comment by alexander-vitishchenko** [comment]
Closed the issue, as no details have been provided by the requestor
