### ISSUE TITLE
Error while fetching Fibaro HC3 events "End of file"

### ISSUE THREAD

**Issue by rico0260** [alexander-vitishchenko/hc3-to-mqtt#43]
Hello, I have a problem with the QuickApp, it stops without any reason apparently.

I attach the Error log (stopped after a few minutes of commissioning):
apparently occurs in 'function QuickApp:readHc3EventAndScheduleFetcher())

[08.01.2023] [12:25:50] [ERROR] [QUICKAPP555]: Error while fetching Fibaro HC3 events "End of file"
[08.01.2023] [12:25:50] [DEBUG] [QUICKAPP555]:
[08.01.2023] [12:25:50] [DEBUG] [QUICKAPP555]: ------- Disconnected from Fibaro HC3
[08.01.2023] [12:25:50] [DEBUG] [QUICKAPP555]:
[08.01.2023] [12:25:50] [DEBUG] [QUICKAPP555]: ------- Disconnected from MQTT (Home Assistant)

have a nice day.

**Comment by rico0260** [comment]
I changed the delay from 100ms to 1000ms like in the previous version and it seems to work better now.

![image](https://user-images.githubusercontent.com/12649196/211202473-03f5d225-5045-452e-aad0-bd9f4adfb18d.png)

so to follow

**Comment by alexander-vitishchenko** [comment]
Just to clarify - does it work better, or the issue is completely gone after changing the delay interval?

**Comment by alexander-vitishchenko** [comment]
@rico0260 I think I know what might cause the issue, and I plan to introduce the fix without 1000ms delays for HC3 => MQTT event transmission (so it propagates events faster. Just need to wait until my home lab in Kyiv has electricity restored)

**Comment by rico0260** [comment]
First answer:
Yes, there is no more problem, I could confirm tomorrow evening if it still works without problem!
Looks good to not have the problem for me anymore.

second answer:
Ok, no problems for future changes.

**Comment by rico0260** [comment]
Can't wait to give feedback on the delay change.
I confirm that for several hours the quickApp has not stopped.

**Comment by alexander-vitishchenko** [comment]
Done - further improved the speed of event transfer, while having safe multithreaded environment for HC3 event polling

**Comment by rico0260** [comment]
For me it works fine with version 1.0.203 (no more <Error while fetching Fibaro HC3 events "End of file">)
