### ISSUE TITLE
Problem with a keyFOB remote control in automations in HA

### ISSUE THREAD

**Issue by rico0260** [alexander-vitishchenko/hc3-to-mqtt#44]
To test one of my keyFOB remotes in HA, I created a simple automation to turn on a light.

I attach screenshots ->

1. In the MQTT integration the information of the pressed button is displayed (example button 2).
![image](https://user-images.githubusercontent.com/12649196/211207291-32734eb2-5d71-4608-aeac-eebb55cf0807.png)

2. Automation:
![image](https://user-images.githubusercontent.com/12649196/211207340-889c0efe-7ba0-4cc3-a55b-c02ed5183054.png)

![image](https://user-images.githubusercontent.com/12649196/211207358-98163b89-bf58-4c96-a31d-9b60230de215.png)

3. but nothing happens in the trace (button 2 doesn't seem to trigger automation).

Am I us

**Comment by rico0260** [comment]
Other information:

the light is well controlled from HA:
![image](https://user-images.githubusercontent.com/12649196/211207842-78b6d220-5bc6-4a17-a26c-706294dd5ba4.png)

![image](https://user-images.githubusercontent.com/12649196/211208004-a5130673-f25d-4e0c-b4bc-1ea6391bd5d7.png)

But no trigger produced in the automation of HA with the remote control.

**Comment by MomosX** [comment]
The remote is created in HA as a sensor. So that should be the trigger.

I'm attaching one of my automations using the same remote which works perfect - 1554 is the remote

'''
alias: Remote 
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.1554
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: sensor.1554
            state: 1-button_long_press
        sequence:
          - service: homeassistant.turn_on
            data: {}
            target:
              entity_id:
                - switch.780
      - conditions:
          - condition: state
            entity_id: sensor.1554
            state: 2-button_long_press
        sequence:
          - service: homeassistant.turn_on
            data: {}
            target:
              entity_id:
                - switch.1282
      - conditions:
          - condition: state
            entity_id: sensor.1554
            state: 3-button_long_press
        sequence:
          - service: homeassistant.turn_on
            data: {}
            target:
              entity_id:
                - switch.1350
      - conditions:
          - condition: state
            entity_id: sensor.1554
            state: 4-button_long_press
        sequence:
          - service: switch.toggle
            data: {}
            target:
              entity_id:
                - switch.1660
mode: single
'''

**Comment by rico0260** [comment]
Yes, indeed it works like that.

**Comment by MomosX** [comment]
great. another closed issue :)

**Comment by alexander-vitishchenko** [comment]
@rico0260, @MomosX  - just to clarify, Fibaro Remote controllers is not just a "sensors" :-)

There is a native trigger/automation integration with Home Assistant, see screenshot

![image](https://user-images.githubusercontent.com/1070777/211219345-ad3e290f-f317-4ec5-b28b-146aeb9ceb83.png)

**Comment by rico0260** [comment]
Yes, I did a second automation, but the trigger does not occur when using the remote control!

![image](https://user-images.githubusercontent.com/12649196/211220323-607e19e1-c54c-4c69-a037-b74149dc703b.png)

![image](https://user-images.githubusercontent.com/12649196/211220269-cb8f929d-3662-4d3f-8a24-b700d011cb21.png)

![image](https://user-images.githubusercontent.com/12649196/211220536-ccf82521-f4ff-419f-b9e5-24dfe099dfce.png)

Do you need more information to verify?
