### ISSUE TITLE
Unable to discoverDeviceHierarchy

### ISSUE THREAD

**Issue by rjclocks** [alexander-vitishchenko/hc3-to-mqtt#45]
New user setup and I am running into a problem with the device discovery not completing.
The connection to my MQTT broker is working (regular updated messages to homeassistant\hc3-dead topic).

Running 1.0.203 from this site and HC3 5.130.64

The initialsation process for device discovery is not completing but gives no error message. 
The following shows all the detail I get through the console:

`[14.01.2023] [15:41:32] [DEBUG] [QUICKAPP284]:`
`[14.01.2023] [15:41:32] [DEBUG] [QUICKAPP284]: ------- Connected to MQTT (Home Assistant)`
`[14.01.2023] [15:41:32] [DEBUG] [QUICKAPP284]: Bridge mode: PRODUCTION`
`[14.01.2023] [15:41:32] [WARNING] [QUICKAPP284]: Variable deviceFilter not found`
`[14.01.2023] [15:41:32] [DEBUG] [QUICKAPP284]: All is good - default filter applied, where only enabled and visible devices are used`
`[14.01.2023] [15:41:32] [DEBUG] [QUICKAPP284]: Filter: {"filters":[{"value":[true],"filter":"enabled"},{"value":[true],"filter":"visible"}],"attributes":{"main":["id"]}}`
`[14.01.2023] [15:41:35] [DEBUG] [QUICKAPP284]: [BinarySensor.init] Uknown doow/window sensor 193 Shop Door`

I tried to add in some debug messages around the code to isolate where it is stopping, but cannot chase it through yet. The odd part is the lack of error messages in the console.

**Comment by alexander-vitishchenko** [comment]
Hi @rjclocks,

Can you please try using the latest 1.0.211 version, and tell if the issue persists or solved?

Do you have any Nice or Zigbee devices, or only Z-Wave and QuickApps?

**Comment by rjclocks** [comment]
I have tried the version you asked and have the same issue.
I do have one Zigbee lightbulb registered on my HC3, but it isn't available most of the time as it is currently only switched on briefly using a Z-Wave socket.
Everything else is Z-Wave on the system.

**Comment by alexander-vitishchenko** [comment]
Hi @rjclocks 

Only Z-Wave are supported at the moment, and adding Zigbee devices would be a new feature. 

1. Can you please provide me your device description, so I can see if this something easy to do or complex? See "Want to propose a new device support? Click here" section at the home page https://github.com/alexander-vitishchenko/hc3-to-mqtt
2. I'll improve logging so QuickApp doesn't break when dealing with Zigbee

**Comment by rjclocks** [comment]
Thanks for the help with getting it sorted.
I will drop the information on there tomorrow and will close this issue.
