### ISSUE TITLE
Propose new device support (Zigbee RGB bulb)

### ISSUE THREAD

**Issue by rjclocks** [alexander-vitishchenko/hc3-to-mqtt#46]
Here are the details of an Ajax Online smart Zigbee Pro GU10 RGBCW spotlight bulb added to HC3.

Included are Swagger/JSON details and Device viewer screenshots.

Importance is low (I don't actually control this device through the HC3, but it is in the infrastructure for testing).

[Zigbee_Lamp_Swagger_response.json.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/10439230/Zigbee_Lamp_Swagger_response.json.txt)

![Zigbee_Device_HC3_Details](https://user-images.githubusercontent.com/6471428/213008122-99160395-c211-48e5-9324-627f6578f178.png)

**Comment by alexander-vitishchenko** [comment]
Hi @rjclocks,

I can see device JSON description for #237 (parent/aggregator device), can you please also send me JSON for #238 which is expected to represent RGBW lamp properties?

**Comment by rjclocks** [comment]
Sure thing. Here you go. 
Sorry I forgot that part.

[Zigbee_Lamp_Swagger_response_ChildDevice.json.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/10474323/Zigbee_Lamp_Swagger_response_ChildDevice.json.txt)

**Comment by alexander-vitishchenko** [comment]
@rjclocks 

I've added experimental Zigbee RGBW device support to the latest release, can you please check it out?

It should theoretically support other types of Zigbee devices too, if you have it for testing in your environment?

**Comment by rjclocks** [comment]
That is now working as expected.
Thank you for adding this.


The only odd thing is that the RGB values are shown as real instead of integer values.  But, in checking that through, it is a Fibaro issue rather than your QA.

![MQTT_Data](https://user-images.githubusercontent.com/6471428/213925430-c7398203-8318-43e5-bef4-fadff679c2be.png)

**Comment by alexander-vitishchenko** [comment]
Does HC3 <-> Home Assistant integration for Zigbee RGBW without rounding?

If not and rounding is a must have - I can tell you where to add rounding in the code, and we see if helps to fix the issue?

**Comment by rjclocks** [comment]
I don't know if it is actually a problem, as I don't have the Home Assistant side of things setup yet. 
My first step was to get data out of my HC3, which I had never got working before. (In this case using MQTT)
Second step is to try to work out how to get the MQTT data into HA in a useful way.

**Comment by alexander-vitishchenko** [comment]
It looks like you already have MQTT broker installed, as addon within Home Assistant, right?

The final step is to enable MQTT Integration in your Home Assistant, and make it connect to same MQTT Broker that is used by the QuickApp

This QuickApp will automatically import devices/entities from Fibaro HC3 to Home Assistant, with no manual efforts required

**Comment by rjclocks** [comment]
That's almost correct. I have an MQTT broker running, but NOT through Home Assistant, so I need to work out how to add/link the MQTT integration within HA to my broker.
It shouldn't be too tricky, but I am a real HA noob at the moment. I will get there.
Thanks for your pointers.

**Comment by alexander-vitishchenko** [comment]
Here goes the guide how Home Assistant can get devices/entities from MQTT - https://www.home-assistant.io/integrations/mqtt/

**Comment by rjclocks** [comment]
Thank you. I will play around with that and see how it goes.

**Comment by alexander-vitishchenko** [comment]
Please let me know if you need further support or we can close the ticket

**Comment by alexander-vitishchenko** [comment]
Closed as outdated
