### ISSUE TITLE
After update from 1.0.221 to 1.0.225 cover/curtain does not work anymore.

### ISSUE THREAD

**Issue by rwijbenga** [alexander-vitishchenko/hc3-to-mqtt#49]
Hi, 

My curtains do not work anymore from Home Assistant after updating to 1.0.225, I think something got messed up in the update.

For example cover.899 has now the status unknown. The Energy and Power sensor for that same cover are still working.  

And in the home assistant log I see these error's:

Entity cover.899 does not support this service.

Error executing service: <ServiceCall cover.open_cover (c:01GVZAKNFSKN10ZKAPKD6BHDAZ): entity_id=['cover.899']>

Anything I can test / try to help with debug?

With kind regards,

Remco

**Comment by alexander-vitishchenko** [comment]
Hi @rwijbenga 

Thank you for finding the issue fast.

I'm continuously extending the QuickApp foundation and I thought it would be great to add Zigbee and Nice devices support, not just  focusing on Z-Wave 😄

Please can you share JSON files for you shutter device? One JSON per state of a shutter, e.g. open, close, 30% position, etc

Just fyi in case you are interested in more context:
- I live in Berlin now and my home laboratory/devices are at Kyiv. This limits the ability to test certain features and device types like I used to do in the past
- automated regression testing framework for CI/CD pipeline has ~70% coverage at best, as I designed and implemented it after my relocation to Berlin

**Comment by alexander-vitishchenko** [comment]
Hi @rwijbenga,

1) It looks like your Fibaro shutter device doesn't properly describe supported actions, so the QuickApp doesn't inform Home Assistant about possibility to use open/close/stop actions. 

2) It would be great if device manufacturer fixed their firmware and used proper list of supported actions... but I believe this might take a lot of time (if done at all), so perhaps I need to adjust the QuickApp with always enabling support open/close/stop actions regardless.

Please check the latest version attached and let me know if it works for you?

**Comment by alexander-vitishchenko** [comment]
It would be great if you could run MQTT Explorer (connected to your MQTT broker), and shared two sets of JSON files - for the latest QuickApp version, and for 1.0.221:
- homeassistant/cover/<id>/config
- homeassistant/cover/<id>/config_json_attributes
- homeassistant/cover/<id>/events/fibaro => home assistant/state
- homeassistant/cover/<id>/events/fibaro => home assistant/value

**Comment by rwijbenga** [comment]
Here is the MQTT output difference between 221 and 229, if you need more let me know.

[explorer output.zip](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/11095043/explorer.output.zip)

**Comment by rwijbenga** [comment]
Let's hope you can find a solution for the mess the module producers make with not having an uniform command system / structure.

Will test when you have something.

**Comment by Sukciukas** [comment]
hello , I have question regarding fibaro roller shutter. i have venetian blinds -in fibaro home center i can move blind up and down with other slider i can open or close slats. in home assistant there is no possibility to open or close slats, only move blind up or down. is it possible to have something similar in home assistant as i have set up card with two sliders, but getting error when trying to change slats possition.


![image](https://user-images.githubusercontent.com/106014840/228540934-6fecc36f-0c16-4dba-a288-843f4b086bb1.png)

![image](https://user-images.githubusercontent.com/106014840/228539602-c0e4febd-9b43-4ff1-a2cf-e101066d5d30.png)

**Comment by alexander-vitishchenko** [comment]
Hi @rwijbenga,

Please check the latest QuickApp version and let me know if it works for you?

**Comment by rwijbenga** [comment]
Works ! :)
