### ISSUE TITLE
Control HA devices back from HC3

### ISSUE THREAD

**Issue by sergiobaiao** [alexander-vitishchenko/hc3-to-mqtt#50]
Hi there, 

Is there anyway i could control devices already on HA (from any other system, like Lutron) on the HC3 using HC3 as a MQTT client that controls HA devices?

**Comment by alexander-vitishchenko** [comment]
HI @sergiobaiao, not at the moment but this looks theoretically feasible in the future, if there are enough backers for the functionality.

I'd suggest to move the topic to the Discussions module of the GitHub project, due to no issue with the existing functionality for HC3 devices managed from HA?

**Comment by sergiobaiao** [comment]
this would be awesome. If i can help someway, let me know

Please move the topic there. I really misplaced it here

**Comment by alexander-vitishchenko** [comment]
Hi @sergiobaiao,

There are several ways you can help, but none of them is easy ;-)
1. Find a community of users who might need the integration, as this particular use-case doesn't seem to be on demand. People look for the possibility to manage all devices from Home Assistant, not vice versa 
2. See if there is anyone who is willing to do the integration for free (you or anyone else), and then I help with the Lua code integration
3. If there are no volunteers to work for free, and you need to have the integration this year/quarter - I can do the development using commercial rates

Feel free to raise a new topic at the "Discussions" module if you think it make sense to invest time into it.
