### ISSUE TITLE
Can't find a way to filter more than one device

### ISSUE THREAD

**Issue by CorceiroPT** [alexander-vitishchenko/hc3-to-mqtt#54]
Hi!

I'm trying to filter more than one device on the DeviceFilter local variable, but it only filter the first Device Id.

My DeviceFilter var looks like this:
{"filter":"deviceID", "value":[268]}, {"filter":"deviceID", "value":[269]}

Only DeviceId 268 gets to the HA... I would like to get only deviceId from 268 to 271, but I can't do that.

I also tried to create DeviceFilter2 and so on to add the other deviceID, but it also don't work.

Can you help me?

**Comment by alexander-vitishchenko** [comment]
Hi @CorceiroPT,

Sure, you just need to use the filter criteria differently. Have you had a chance to check Fibaro API?

I believe they expect the filter like **{"filter":"deviceID", "value":[268, 269]}**

**Comment by CorceiroPT** [comment]
It worked!
Thank you very much. Didn't know that was the correct way to do it.
I used {"filter":"deviceID", "value":[268,269,270,271]} and it worked as I wanted, geting only the 268 to 271 devices to pass to HA.
Thank you very much.
