### ISSUE TITLE
Duplicates in home assistant for same device

### ISSUE THREAD

**Issue by EzequielPitton78** [alexander-vitishchenko/hc3-to-mqtt#55]
**Describe the bug**
MQTT Integration in Homeassistant creates duplicate/alternate entity for the same fibaro device:

![image](https://github.com/alexander-vitishchenko/hc3-to-mqtt/assets/88885392/03f3f8c5-2f0b-4108-964d-9169ce67758f)

**How to reproduce?**
After remove the integration, clear MQTT and reconfigure and restart quickapp, works, but after some time happens again. Automations in node red stop working because the reference is invalid. 
Happens in  ~60 devices of ~ 350 total devices, seems irrespective of type and controller (below listed)
 
[duplicates.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/12208642/duplicates.txt)

**Expected behavior**
No duplicates

**Environment:**
 - QuickApp version latest stable (1.0.230 )
 - Fibaro hardware: Home Center 3:  1 Master, 4 Slaves, ~ 350 devices
 
![image](https://github.com/alexander-vitishchenko/hc3-to-mqtt/assets/88885392/02885224-5ea6-421c-a870-95ad1524ca01)
 
![image](https://github.com/alexander-vitishchenko/hc3-to-mqtt/assets/88885392/7c3115af-0342-43a3-a3d0-22f88dc1f51e)

**Attach QuickApp logs**
- Open Fibaro Home Center 3 in a web-browser
- Home Screen > Logging (left-bottom panel) > enable filter by QuickApp id
- Copy log records starting from "------- HC3 <-> MQTT BRIDGE"
[fibaro_log.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/12207821/fibaro_log.txt)
![repeated](https://github.com/alexander-vitishchenko/hc3-to-mqtt/assets/88885392/979d7efe-b71b-4679-852c-23f2bfe14705)

**Attach Home Assistant logs**
Attach Home Assistant Core and MQTT integration logs.

[home-assistant_2023-07-30T06-57-58.717Z.zip](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/12208649/home-assistant_2023-07-30T06-57-58.717Z.zip)

[home-assistant_mqtt_2023-07-30T06-48-20.218Z.zip](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/12208643/home-assistant_mqtt_2023-07-30T06-48-20.218Z.zip)

**Comment by alexander-vitishchenko** [comment]
Hi @EzequielPitton78,

I have some thoughts why it may happen in your environment, but need to get full logs from Fibaro, can you please share full logs after the QuickApp restart? (starting from the line "------- HC3 <-> MQTT BRIDGE")

Thank you,
Alexander

**Comment by EzequielPitton78** [comment]
[FIbaro_Log_Complete.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/12214234/FIbaro_Log_Complete.txt)

Thank you very much!!! Attached!

**Comment by alexander-vitishchenko** [comment]
Hi @EzequielPitton78,

It looks like the QuickApp works as it should at first glance.

I'd suspect your MQTT might have duplicates caused by the device types change, i.e. the old device retained in the MQTT, while Fibaro firmware or the newer version of the QuickApp broadcasted the same device id but for another device type.

I'd expect this steps to help you, if the assumption above is correct:
1. Stop the QuickApp
2. Clear MQTT topics under "homeassistant" (you can use "MQTT Explorer" desktop app)
3. Start the QuickApp

Please let me know the results.

**Comment by EzequielPitton78** [comment]
Instructions followed. Just cleaned all MQTT homeassistant topic, re launched QuickApp. No duplicates now, will check if they appear again and report back. 

Devices containing 1604 amd 1283:

![image](https://github.com/alexander-vitishchenko/hc3-to-mqtt/assets/88885392/a843809b-c47c-40ee-8187-a95afa70c8ef)

![image](https://github.com/alexander-vitishchenko/hc3-to-mqtt/assets/88885392/521310d4-23d7-4d36-b201-43576d0f5261)

**Comment by alexander-vitishchenko** [comment]
Great! Please let me know if you still need help, and I'd assume the issue is resolved for now

**Comment by EzequielPitton78** [comment]
Hi, unfortunately duplicates appeared again:

![image](https://github.com/alexander-vitishchenko/hc3-to-mqtt/assets/88885392/889400b7-1caf-4681-80bf-a5b7f819df34)

[2023_08_02_duplicates_mqtt.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/12237204/2023_08_02_duplicates_mqtt.txt)

**Comment by EzequielPitton78** [comment]
[duplicate_comparison.xlsx](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/12237423/duplicate_comparison.xlsx)

The duplicates appeared on different divices. Interesting they are 58 in both days. Will repeat the elimination of MQTT topics and relaunch QuickApp to have more data

**Comment by rudi70** [comment]
> Hi, unfortunately duplicates appeared again:
> 
> ![image](https://user-images.githubusercontent.com/88885392/257732642-889400b7-1caf-4681-80bf-a5b7f819df34.png)
> 
> [2023_08_02_duplicates_mqtt.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/12237204/2023_08_02_duplicates_mqtt.txt)

Hi! maybe theer is a topic in your HA (between MQTT-server and HA)? this, you could check in the MQTT-Explorer.... mybe it's not a topic from the Fibaro-side....
kr, Rudi

**Comment by EzequielPitton78** [comment]
Restarted, crashed QuickApp, started again 

[02.08.2023] [12:22:55] [DEBUG] [QUICKAPP2285]: ------- Disconnected from Fibaro HC3
[02.08.2023] [12:22:56] [DEBUG] [QUICKAPP2285]:
[02.08.2023] [12:22:56] [DEBUG] [QUICKAPP2285]: ------- Disconnected from MQTT/Home Assistant


[2023_08_02_Fibaro_Log_Complete.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/12239067/2023_08_02_Fibaro_Log_Complete.txt)

**Comment by EzequielPitton78** [comment]
Restarted all HC3 controllers, deleted all MQTT topics, relaunched the QuickApp.
Works and no duplicates in HA. Let's see when/if they appear again.


[02.08.2023] [12:38:47] [DEBUG] [QUICKAPP2285]:
[02.08.2023] [12:38:47] [DEBUG] [QUICKAPP2285]: ------- Fibaro device configuration and states have been distributed to MQTT/Home Assistant in 12 second(s)
[02.08.2023] [12:38:47] [DEBUG] [QUICKAPP2285]:
[02.08.2023] [12:38:47] [DEBUG] [QUICKAPP2285]: ------- Connected to Fibaro Home Center 3 events feed
[02.08.2023] [12:38:51] [DEBUG] [QUICKAPP2285]: Turn OFF for device #1711
[02.08.2023] [12:38:51] [DEBUG] [QUICKAPP2285]: Turn OFF for device #2163
[02.08.2023] [12:38:51] [DEBUG] [QUICKAPP2285]: Turn OFF for device #2164


![image](https://github.com/alexander-vitishchenko/hc3-to-mqtt/assets/88885392/99a65c60-ee0e-4e90-9934-fb6e88ea95ad)

**Comment by alexander-vitishchenko** [comment]
Can you please share a full MQTT Info from your Home Assistant? Setting => Devices & Entities => click at "X entities" for MQTT integration => pick two sample duplicates => for each of 2 entities => click at three dots => Device Info => follow screenshots

Step 1
<img width="1278" alt="image" src="https://github.com/alexander-vitishchenko/hc3-to-mqtt/assets/1070777/27cbf630-ee48-4eae-87f9-0c6904d43d3a">


Step 2
<img width="727" alt="image" src="https://github.com/alexander-vitishchenko/hc3-to-mqtt/assets/1070777/5c19377e-a303-4fe5-97d7-0e882cece226">

**Comment by EzequielPitton78** [comment]
Hello,
       Interesting finding: affected devices change from one ocurrence to other, but the 3 times deleted and re-run, always appear exactly 57 entities renamed with the "_2" suffix in HA!  That's indicative it may not have relation to the devices themselves and more of some numeric limit somewhere instead, right?   I say renamed because the original without the suffix desapears from HA. 

[duplicate_comparison.xlsx](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/12245218/duplicate_comparison.xlsx)

Below the MQTT diagnostic from 2 devices with "_2" suffix. The originals without the suffix are not present anymore.

[light.1591_2.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/12245217/light.1591_2.txt)
[binary_sensor.1669_2.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/12245234/binary_sensor.1669_2.txt)

**Comment by alexander-vitishchenko** [comment]
One clarification, when you see the entities at Home Assistant for "1591_2" and "1669_2" - are there any entities named as "1591" and "1669", and can you extract MQTT info for them?

**Comment by EzequielPitton78** [comment]
Hello!  There originals "1591" and "1669" are not in HA anymore. Sorry I should have explained myself better.

**Comment by alexander-vitishchenko** [comment]
Hi @EzequielPitton78, it looks like I need more information for investigation. Luckily we may potentially get it from another report #56. 

As I understood - another QuickApp user might be facing a similar situation because of the Home Assistant upgrade to the newer version that seems to be using a newer version of the MQTT spec. 

Maybe you can do it faster than another user, and can share Home Assistant MQTT logs with the warning messages that are mentioned at #56?

**Comment by EzequielPitton78** [comment]
Hello! 

In my case de MQTT warning from HA only shields 1 error and is not from this quickapp: I normally name each fibaro device with the manufacturer/model so no coincidence possible. "Friendly name" of entities appear as a concatenation with new HA MQTT interpretation and is quite ugly. Probably wiill revert back to id number only. 

![image](https://github.com/alexander-vitishchenko/hc3-to-mqtt/assets/88885392/c16e7d10-1874-4115-b70d-32c5bbe80358)

Is there any other data extraction that I could make to support your investigation?

Some MQTT entities have an entity name equal to the device name. This is not expected. The entity name is set to null as a work-a-round to avoid a duplicate name. Please inform the maintainer of the software application that supplies the affected entities to fix this issue.

List of affected entities:

update.radar_cocina_interior

**Comment by LodeBo** [comment]
I have exactly the same problem but in my case it's always with the same devices.
As long as i don't login to the Fibaro controller everything is fine but as soon as i login the problems begin.
Strange.....

**Comment by alexander-vitishchenko** [comment]
I see the warning messages in logs, it looks like there is no problem with device and entity having the same name, as they are separated by separate Device and Entity screens.

Can you please send me full QuickApp logs from Fibaro HC3? i.e. enable logging, restart QuickApp, share logs with me.

fyi - I was thinking about automating unique names generation by the newer version of the QuickApp, but it may cause more harm to meaningful naming then helping. The best way would be to name Fibaro device/entities in a way there is no duplication.

**Comment by alexander-vitishchenko** [comment]
I could reproduce the issue and working on a fix now

**Comment by alexander-vitishchenko** [comment]
Ready, you need to do the following:
- stop the existing QuickApp
- clean your MQTT for "/home assisstant/**"
- upload & start new version of the QuickApp

**Comment by LodeBo** [comment]
Hi Alexander,
Thanks for the update.
I installed the new version of the QuickApp today.

Until now it works fine.
I will give you an update in a couple of weeks.

Stay save !
