### ISSUE TITLE
Discovered entities with a name that starts with the device name

### ISSUE THREAD

**Issue by xp1ratex** [alexander-vitishchenko/hc3-to-mqtt#56]
**Describe the bug**
As of Home Assistant 2023.8.0 u get a varning about the naming of MQTT entities

Some MQTT entities have an entity name that starts with the device name. This is not expected. To avoid a duplicate name the device name prefix is stripped of the entity name as a work-a-round. Please inform the maintainer of the software application that supplies the affected entities to fix this issue.

List of affected entities:

sensor.52_batterylevel
sensor.53_batterylevel
light.44
binary_sensor.51
sensor.49_energy
sensor.39_energy
sensor.49_power
sensor.34_power
sensor.23_energy
sensor.63_power
sensor.66
light.76
sensor.57_batterylevel
binary_sensor.57
sensor.58_batterylevel
sensor.39_power
sensor.72
sensor.37_energy
sensor.35_power
sensor.44_power
sensor.59
sensor.47_energy
light.35
sensor.28_power
sensor.28_energy
sensor.59_batterylevel
light.34
sensor.34_energy
sensor.58
light.39
sensor.47_power
light.49
sensor.52
light.37
sensor.23_power
light.47
sensor.37_power
light.63
light.23
sensor.53
light.28
sensor.51_batterylevel
sensor.63_energy

Dont know if theres a user error from me or do we need to take some sort of action to get the MQTT naming correct?

**How to reproduce?**
Steps to reproduce the behavior like:
1. Upgrade Home Assistant to 2023.8.0 or later
2. Click on settings
3. Open repair message about mqqt

**Expected behavior**

**Environment:**
 - QuickApp version 1.0.230
 - Fibaro hardware: Home Center 3 Lite, 5.140.17

**Attach QuickApp logs**
- Open Fibaro Home Center 3 in a web-browser
- Home Screen > Logging (left-bottom panel) > enable filter by QuickApp id
- Stop and then start the QuickApp
- Copy log records starting from "------- HC3 <-> MQTT BRIDGE"

**Attach Home Assistant logs**
Attach Home Assistant Core and MQTT integration logs.

**Comment by alexander-vitishchenko** [comment]
Hi @xp1ratex, I see and this might be important, can you please share Home Assistant logs with the warning messages that you mentioned above?

**Comment by xp1ratex** [comment]
Yeah i have set my devices with names in Fibaro HC3L, i add the complete log here and a screenshot of my devices in HCL3. 
Hope it helps.
[home-assistant_2023-08-13T20-04-43.878Z.log](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/12330310/home-assistant_2023-08-13T20-04-43.878Z.log)
![Skärmbild 2023-08-13 220819](https://github.com/alexander-vitishchenko/hc3-to-mqtt/assets/65679573/0ae71343-e760-4f7f-8aea-ca393a9b8d05)

**Comment by MomosX** [comment]
I can confirm the issue.  But it only seems to hapen with QuickApps or devices which have not been renamed after inclusion.
For me it's the QA's.  they have different name then their ID, but the error still pops up.

**Comment by alexander-vitishchenko** [comment]
@xp1ratex I see the warning messages in logs, it looks like there is no problem with device and entity having the same name, as they are separated by separate Device and Entity screens.

Can you please send me full QuickApp logs from Fibaro HC3? i.e. enable logging, restart QuickApp, share logs with me.

fyi - I was thinking about automating unique names generation by the newer version of the QuickApp, but it may cause more harm to meaningful naming then helping. The best way would be to name Fibaro device/entities in a way there is no duplication.

**Comment by xp1ratex** [comment]
> @xp1ratex I see the warning messages in logs, it looks like there is no problem with device and entity having the same name, as they are separated by separate Device and Entity screens.
> 
> Can you please send me full QuickApp logs from Fibaro HC3? i.e. enable logging, restart QuickApp, share logs with me.
> 
> fyi - I was thinking about automating unique names generation by the newer version of the QuickApp, but it may cause more harm to meaningful naming then helping. The best way would be to name Fibaro device/entities in a way there is no duplication.
[quickapp debug.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/12506790/quickapp.debug.txt)

Is this what u need?

**Comment by xp1ratex** [comment]
Ill try it later today, a quick question is there any way to update or do i need to remove and install?Den 4 sep. 2023 12:44 skrev Alexander Vitishchenko ***@***.***>:
Yes it helps. I've just released the new version of the QuickApp, please let me know if it works for you?

**Comment by alexander-vitishchenko** [comment]
Hi @xp1ratex, can you please advise if this is still relevant for you, and did you try using https://www.home-assistant.io/integrations/fibaro/? Curious to see how many devices are supported, besides it might be simpler to configure without MQTT

**Comment by xp1ratex** [comment]
> Hi @xp1ratex, can you please advise if this is still relevant for you, and did you try using https://www.home-assistant.io/integrations/fibaro/? Curious to see how many devices are supported, besides it might be simpler to configure without MQTT

Iirc homeassistant turned of that logging thus not showing the error anymore, i tried to search my logs for it but i didnt get any matches, so i guess its working (or is hidden) but i think there will be some problem with it in 2025.1 cause thats where this namings will change. But as for now i dont see the error, i havent tried any other integration but as for now the mqtt version works fine.

**Comment by alexander-vitishchenko** [comment]
Great! And so we should be good to go with the ticket closure
