### ISSUE TITLE
Devices unavailable after HA restart  

### ISSUE THREAD

**Issue by Nikus54** [alexander-vitishchenko/hc3-to-mqtt#6]
Hello.
Great job. It works great for me.
Just a problem when I restart home assistant, the devices become "unavailable".
I tried to use the mqtt.publish service from home assistant, it is possible to send a value to the HC3.
The only way to get an "available" status in home assistant is to relaunch the quickapp.
Can you help me on this point?
Thank you.
Nico

**Comment by alexander-vitishchenko** [comment]
Hi @Nikus54!

I've just tested Home Assistant restart as a service, and rebooting host completing (via webinterface and ssh) => my Fibaro HC3 devices become available after restart in Home Assistant

Perhaps we can have a Zoom call... so you share your screen and I can get more information to reproduce and fix the issue?

**Comment by alexander-vitishchenko** [comment]
Closed as couldn't reproduce the issue and no response from the requestor
