### ISSUE TITLE
Energy/Power API support

### ISSUE THREAD

**Issue by alexander-vitishchenko** [alexander-vitishchenko/hc3-to-mqtt#8]
Created on behalf of @rwijbenga:

Implement Energy/Power API integration for HC3 => Home Assistant

**Comment by rwijbenga** [comment]
Super! 

Keep up the great work.

**Comment by alexander-vitishchenko** [comment]
@rwijbenga 

Just to keep you updated - I’ve implemented Energy API support at my local development environment

I’ll be doing extra testing testing next weekend, and then publish changes along with few other improvements at once

**Comment by rwijbenga** [comment]
Exciting news! 

I think this is going to be a very good plugin for many new users.... :)

**Comment by alexander-vitishchenko** [comment]
Implemented both Energy and Power monitoring for Fibaro HC3 devices marked with interfaces "energy" (as kWh) and "power" (as W)

**Comment by alexander-vitishchenko** [comment]
@rwijbenga new Energy/Power API works well for me. Feel free to check it out on your end, and let me know if all is good or any issues to be fixed

**Comment by rwijbenga** [comment]
Great work again! 

Did a small test, and it works.. Only small thing.... 

They changed a device class:

https://developers.home-assistant.io/blog/2021/08/16/state_class_total/

So I changed "measurement" to "total_increasing" in your script to resolve the error message. 

https://community.home-assistant.io/t/how-can-i-add-total-increasing-to-my-template-sensor/334961/14

So a simple change for you to do in your build.... ;)


Now testing some devices over a longer period, to be sure.

**Comment by alexander-vitishchenko** [comment]
Right... Home Assistant team keeps adjusting the specification. This is fine, because it is an evolutionary process that makes platform a better/cleaner place to work with.

+ it appears that "last_reset" property needs attention too, based on the docs from you + logs from my Home Assistant "2021-09-06 01:11:50 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.svet_gostinaia (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) with state_class measurement has set last_reset. Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11. Please update your configuration if state_class is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22"

I'll apply the changes this weekend. And I also plan to check Home Assistant logs for warning messages more frequently :)

**Comment by alexander-vitishchenko** [comment]
I’ve implemented the changes to total_increasing and last_reset properties. Doing local testing and then vomit changes during weekend
